### ISSUE TITLE
Switch in class method crashes

### ISSUE THREAD

**Issue by srgraham** [za-creature/coffeescope#12]
I'm running version 0.2.3 of coffeescope against some of my work projects. I'm getting this error, which I think happens because of a switch inside a class method. Here's some example code that causes a crash:

``` coffee
class Abc
  someFunc: (str)->
    switch str
      when 'something'
        a = 8

```

And here's the error I get

```
scottgra$ coffeelint -f ~/htdocs/coffeelint.json broke.coffee 
/usr/local/lib/node_modules/coffeescope2/lib/Scope.js:121
            return a.first_line < b.first_line || (a.first_line === b.first_line && a.first_column <= b.first_column);
                    ^

TypeError: Cannot read property 'first_line' of undefined
  at isBefore (/usr/local/lib/node_modules/coffeescope2/lib/Scope.js:121:21)
  at checkUsedBeforeDefined (/usr/local/lib/node_modules/coffeescope2/lib/Scope.js:126:18)
  at Scope.module.exports.Scope.appendErrors (/usr/local/lib/node_modules/coffeescope2/lib/Scope.js:140:11)
  at Scope.appendErrors (/usr/local/lib/node_modules/coffeescope2/lib/Scope.js:5:59)
  at ScopeLinter.module.exports.ScopeLinter.newScope (/usr/local/lib/node_modules/coffeescope2/lib/ScopeLinter.js:86:20)
  at ScopeLinter.newScope (/usr/local/lib/node_modules/coffeescope2/lib/ScopeLinter.js:5:59)
  at ScopeLinter.module.exports.ScopeLinter.lint (/usr/local/lib/node_modules/coffeescope2/lib/ScopeLinter.js:46:14)
  at ScopeLinter.lint (/usr/local/lib/node_modules/coffeescope2/lib/ScopeLinter.js:5:59)
  at Coffeescope2.module.exports.Coffeescope2.lintAST (/usr/local/lib/node_modules/coffeescope2/lib/index.js:31:38)
  at ASTLinter.module.exports.ASTLinter.lint (/Library/WebServer/htdocs/github/coffeescope/node_modules/coffeelint/lib/coffeelint.js:613:43)
  at Object.coffeelint.lint (/Library/WebServer/htdocs/github/coffeescope/node_modules/coffeelint/lib/coffeelint.js:370:67)
  at ErrorReport.module.exports.ErrorReport.lint (/Library/WebServer/htdocs/github/coffeescope/node_modules/coffeelint/lib/coffeelint.js:758:51)
  at lintFiles (/Library/WebServer/htdocs/github/coffeescope/node_modules/coffeelint/lib/commandline.js:98:19)
  at Object.<anonymous> (/Library/WebServer/htdocs/github/coffeescope/node_modules/coffeelint/lib/commandline.js:251:21)
  at Object.<anonymous> (/Library/WebServer/htdocs/github/coffeescope/node_modules/coffeelint/lib/commandline.js:256:4)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:142:18)
  at node.js:939:3
```

**Comment by za-creature** [comment]
Having trouble reproducing this; what's your config like?

``` bash
B:\coffeescope2>coffeelint foo.coffee
  ⚡ foo.coffee
     ⚡ #1: Variable "Abc" is never used.
     ⚡ #5: Variable "a" is never used.

⚡ Warning! » 0 errors and 2 warnings in 1 file
```

foo.coffee

``` coffeescript
class Abc
    someFunc: (str) ->
        switch str
            when "something"
                a = 8
```

coffeelint.json

```
"check_scope": {
    "module": "coffeescope2",
    "level": "warn",
    "environments": [],
    "globals": {},
    "overwrite": true,
    "same_scope": false,
    "shadow": true,
    "shadow_exceptions": ["err", "next"],
    "undefined": true,
    "unused_variables": true,
    "unused_arguments": false
}
```

**Comment by srgraham** [comment]
``` json
"check_scope" : {
    "module":"/usr/local/lib/node_modules/coffeescope2",
    "level": "warn",
    "environments": ["builtin","es5","browser","es6","node","mocha","shelljs","jquery"],
    "globals": {
        "jQuery": false,
        "_":false,
        "$":false,
        "moment":false,
        "Backbone":false,
        "BLUE":true,
        "MY_WRITABLE_SUPER_GLOBAL": true
    },
    "overwrite": false,
    "shadow": false,
    "shadow_builtins": false,
    "shadow_exceptions": ["err", "next"],
    "undefined": true,
    "unused_variables": true,
    "unused_arguments": false
  }
```

**Comment by srgraham** [comment]
Hmm, only happens when I use the full module path. Not sure why. Other files lint just fine. I'll just swap it to simply "coffeescope2" as that seems to stop this error. Thanks for the quick response!

**Comment by za-creature** [comment]
I have a feeling this is related to the version of coffeescript bundled with coffeelint; if using the local path, you might be loading a newer local coffeelint whereas specifying the global path will always load the global (potentially older) coffeelint. Can you provide the relevant versions so that I may test against? At the very least, I could make a note of this incompatibility (if that's the culprit)

**Comment by srgraham** [comment]
I ran this command from various directories:
`coffeelint -f ~/htdocs/coffeelint.json ~/htdocs/github/coffeescope/test/ScopeLinter/broke.coffee`
My coffeelint.json has the "module" set as "coffeescope2"

The results of `coffeelint --version` and `coffee --version` are as follows:
random directory (which error) gives me coffeelint@1.12.1 and coffee-script@1.10.0
project directory (which errors) gives me coffeelint@1.15.0 and coffee-script@1.10.0
a git clone of this project (does not error) gives me coffeelint@1.15.7 and coffee-script@1.10.0

Edit: Blah! I'm bad at this. the reason the git clone doesn't fail is it can't find coffeescope2. I'm still looking at this to try to figure out what makes it not die on my system.

**Comment by za-creature** [comment]
I'm at work right now, but after hours I'll give this more time and try to play with versions and whatnot.

**Comment by srgraham** [comment]
After further review, I believe it was caused by a conflict with another coffeelint package.

When moving another package I had installed, "coffeelint-no-implicit-returns", in my coffeelint.json to be after "coffeescope2" the crash has gone away.
I'm guessing there's some modification of underlying properties within that module that was causing it.

**Comment by za-creature** [comment]
Keep this open for now. I definitely want to investigate this further as it may need to be reported somewhere else (the package itself, coffeelint or maybe even coffee-script if some internal function is manipulating the AST without meaning to)

**Comment by za-creature** [comment]
Oh, and thanks for the detective work. Much appreciated!

**Comment by saifelse** [comment]
Maintainer of [coffeelint-no-implicit-returns](https://github.com/saifelse/coffeelint-no-implicit-returns) here. I serendipitously ran into this issue myself--latest release should no longer cause problems!

**Comment by za-creature** [comment]
Cool, thanks!
